# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 14:20
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name=b'Ad Name')),
                ('adtype', models.CharField(choices=[(b'ban_top_wide', b'btw'), (b'ban_right', b'br'), (b'popup', b'popup'), (b'ban_left', b'bl')], max_length=15, verbose_name=b'Ad Type')),
                ('genre', models.CharField(choices=[(b'Gaming', b'Gaming'), (b'Movies', b'Movies'), (b'Auto', b'Auto'), (b'Porn', b'Porn')], max_length=15)),
                ('content', models.URLField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('currency', models.CharField(choices=[(b'eqc', b'EQC'), (b'xqc', b'XQC')], max_length=4)),
                ('asking_rate', models.DecimalField(decimal_places=8, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(12, 8)])),
                ('ask_date_from', models.DateField()),
                ('ask_date_to', models.DateField()),
                ('cpi', models.DecimalField(decimal_places=8, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(12, 8)])),
                ('cpc', models.DecimalField(decimal_places=8, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(12, 8)])),
                ('msg', models.CharField(max_length=300)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qchain_backend.Ad')),
            ],
        ),
        migrations.CreateModel(
            name='Adspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name=b'Adspace Name')),
                ('adtype', models.CharField(choices=[(b'ban_top_wide', b'btw'), (b'ban_right', b'br'), (b'popup', b'popup'), (b'ban_left', b'bl')], max_length=15, verbose_name=b'Ad Type')),
                ('genre', models.CharField(choices=[(b'Gaming', b'Gaming'), (b'Movies', b'Movies'), (b'Auto', b'Auto'), (b'Porn', b'Porn')], max_length=15)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(null=True)),
                ('bio', models.CharField(max_length=300, null=True)),
                ('e_balance', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=12, validators=[django.core.validators.DecimalValidator(12, 8)])),
                ('x_balance', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=12, validators=[django.core.validators.DecimalValidator(12, 8)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('currency', models.CharField(choices=[(b'eqc', b'EQC'), (b'xqc', b'XQC')], max_length=80)),
                ('payout_cap', models.DecimalField(decimal_places=8, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qchain_backend.Ad')),
                ('adspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qchain_backend.Adspace')),
            ],
        ),
        migrations.CreateModel(
            name='RequestForAdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('currency', models.CharField(choices=[(b'eqc', b'EQC'), (b'xqc', b'XQC')], max_length=4)),
                ('asking_rate', models.DecimalField(decimal_places=8, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(12, 8)])),
                ('ask_date_from', models.DateField()),
                ('ask_date_to', models.DateField()),
                ('cpi', models.DecimalField(decimal_places=8, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(12, 8)])),
                ('cpc', models.DecimalField(decimal_places=8, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(12, 8)])),
                ('msg', models.CharField(max_length=300)),
                ('adsp', models.ManyToManyField(to='qchain_backend.Adspace')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField()),
                ('impressions', models.IntegerField(unique_for_date=b'stat_date', validators=[django.core.validators.MinValueValidator(0)])),
                ('clicks', models.IntegerField(unique_for_date=b'stat_date', validators=[django.core.validators.MinValueValidator(0)])),
                ('rpm', models.DecimalField(decimal_places=8, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(12, 8)])),
                ('revenue', models.DecimalField(decimal_places=8, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(12, 8)])),
                ('contract', models.ManyToManyField(to='qchain_backend.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=300)),
                ('genres', models.CharField(choices=[(b'Gaming', b'Gaming'), (b'Movies', b'Movies'), (b'Auto', b'Auto'), (b'Porn', b'Porn')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='adspace',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qchain_backend.Website'),
        ),
    ]
