# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qchain_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestforadv',
            old_name='cpc',
            new_name='cpm',
        ),
        migrations.RemoveField(
            model_name='requestforadv',
            name='asking_rate',
        ),
    ]
