# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-13 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qchain_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='e_balance',
        ),
    ]
