# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qchain_backend', '0002_auto_20171007_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adlisting',
            name='msg',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='agent',
            name='bio',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='requestforadv',
            name='msg',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='website',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
